language: node_js
node_js: node
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  keep-history: true
  local-dir: ./dist
  on:
    branch: master